baseURL = 'https://b.53.workers.dev/'
languageCode = 'zh-cn'
title = '淅淅沥迷'
theme = 'PaperMod'
enableRobotsTXT = true
enableGitInfo = false
hasCJKLanguage = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    lineNos = false
    noClasses = false
    style = 'monokai'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.goldmark.parser]
    [markup.goldmark.parser.attribute]
      block = true
  [markup.asciidocExt]
    backend = 'html5'
    extensions = []
    failureLevel = 'fatal'
    noHeaderOrFooter = true
    preserveTOC = false
    safeMode = 'unsafe'
    sectionNumbers = false
    trace = false
    verbose = false
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]

[sitemap]
changefreq = 'weekly'
filename = 'sitemap.xml'
priority = 0.5

[params]
description = '又一个 WordPress 站点'
author = '淅淅沥迷'
keywords = ['博客', 'Linux', 'DNS', '技术']
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
keys = ["title", "permalink", "summary", "content"]

[params.homeInfoParams]
Title = "淅淅沥迷"
Content = "又一个 WordPress 站点"

[params.comments]
enabled = false

[params.giscus]
repo = "7893/b"
repoID = "R_kgDOQMhOpw"
category = "General"
categoryID = ""
mapping = "pathname"
strict = "0"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "bottom"
theme = "preferred_color_scheme"
lang = "zh-CN"

[[params.socialIcons]]
name = "rss"
url = "/index.xml"

[outputs]
home = ["HTML", "RSS", "JSON"]

[taxonomies]
category = 'categories'
tag = 'tags'

[markup.goldmark.extensions]
typographer = true

[markup.goldmark.extensions.passthrough]
enable = false

[markup.goldmark.extensions.passthrough.delimiters]
block = []
inline = []
